

on:
  push:
    branches:
      - main
    paths:
      - challenge5/**


permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./challenge5
    steps:
      - name: " Github checkout"
        uses: actions/checkout@v3
        with:
          sparse-checkout: challenge4
      - name: "configure aws"
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.challenge5_arn }}
          aws-region: "us-east-1"
      - name: "Terraform setup"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.1
      - name: "terraform init"
        run: terraform init
      - name: "Terraform format"
        run: terraform fmt -check
      - name: "Terraform validate"
        run: terrafomrm validate
      - name: "Terraform plan"
        run: terraform plan
      - name: "terraform apply"
        run: terraform apply --auto-approve
      - name: "update kubeconfig"
        run: aws eks update-kubeconfig --name my-cluster-name --region us-east-1
      - name: "applying config"
        run: |
          kubectl get nodes
          kubectl apply -f kubernetes/